server:
  port: 8762

spring:
  application:
    name: sc-cli
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbs?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#mybatis配置
mybatis:
  typeAliasesPackage: com.wdc.sccli.entity
  mapperLocations: classpath:mapper/*.xml
  #configLocation: classpath:/mybatis-config.xml


